config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/', to: 'pages#home'
  get '/about', to: 'pages#about'

  # resources :sessions, only: [:show, :create, :destroy]

  get '/login', to: 'sessions#show'
  post '/login', to: 'sessions#create'

  # get '/logout', to: 'sessions#destroy'
  # delete '/logout', to: 'sessions#destroy'
  match '/logout', to: 'sessions#destroy', via: [:get, :delete]


  resource :user, except: [:destroy] do
    resource :profile, except: [:destroy]
  end

  resources :profiles do
    member do
    #   # match 'vote/up', 'profiles#vote', via: [:get], direction: 'up'
    #   # match 'vote/down', 'profiles#vote', via: [:get], direction: 'down'
      match 'vote/:direction', to: 'profiles#vote', via: [:get], as: 'vote'
    end
  end

  namespace :admin do
    resources :users, only: [:index] do
      resource :profile
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  has_many :votes
end

app/models/user.rb
require 'bcrypt'

class User < ApplicationRecord
  has_one :profile
  has_many :votes
  
  has_secure_password


end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :user
  belongs_to :profile
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

  before_action do
    if current_user.id != 1
      flash[:notice] = "No Admin for you! RAWR!"
      redirect_to '/'
    end
  end

  def index
    @users = User.all
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  include SessionsHelper
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end

  def about
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  def show
    @profile = current_user.profile || Profile.new
  end

  def new
    @profile = current_user.profile || Profile.new
  end

  def create
    @profile = Profile.new(profile_params)
    @profile.user = current_user
    if @profile.save
      redirect_to user_profile_path
    else
      flash[:notice] = "Nope"
      render 'new'
    end
  end

  def edit
    @profile = current_user.profile || Profile.new
  end

  private

  def profile_params
    params.require(:profile).permit(:breed, :yob, :image_url, :favorite_nap_position, :purr_intensity, :in_to_head_butts)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    if user = User.find_by(email: user_params[:email]).try(:authenticate, user_params[:password])
      session[:user_id] = user.id
      flash[:notice] = "Welcome... purrrrr"
      redirect_to '/'
    else
      flash[:notice] = "Failed to login, try again or have a nap"
      @user = User.new
      render 'show'
    end
  end

  def show
    @user = User.new
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = "Hisss!"
    redirect_to '/'
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = current_user
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user = @current_user || User.find(session[:user_id]) if session[:user_id]
  end

  def is_logged_in?
    current_user != nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/index.html.erb
<h2>Users</h2>

<ul>
  <% @users.each do |user| %>
  <li><%= user.to_s %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>TinderForCats</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/menu' %>
    <%= render 'shared/flash' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
About cats!

app/views/pages/home.html.erb
<p>TODO Funny cat memes</p>

app/views/profiles/_form.html.erb
<%= form_for @profile, url: user_profile_path do |f| %>
<%= f.text_field :breed, placeholder: 'breed' %>
<%= f.text_field :yob, placeholder: 'year of birth' %>
<%= f.text_field :image_url, placeholder: 'image_url' %>
<%= f.text_field :favorite_nap_position, placeholder: 'nap position' %>
<%= f.text_field :purr_intensity %>
<%= f.text_field :in_to_head_butts %>
<%= f.submit %>
<% end %>

app/views/profiles/edit.html.erb
<%= render 'form' %>

app/views/profiles/new.html.erb
<%= render 'form' %>

app/views/profiles/show.html.erb
Profile!
<% if @profile.id.nil? %>
  <%= link_to 'Create Profile', new_user_profile_path %>
<% else %>
<ul>
<% @profile.attributes.each do |k, v| %>
  <li><%= k %> : <%= v %></li>
<% end %>
</ul>
<%= link_to 'Edit Profile', edit_user_profile_path %>
<% end %>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
<div class="alert alert-info alert-dismissible" role="alert">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  <%= flash[:notice] %>
</div>
<% end %>

app/views/shared/_menu.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">

      <a class="navbar-brand" href="/" alt="tinder for cats"><img src="/cat_logo.png"/></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% unless is_logged_in? %>
        <li><%= link_to "Login", login_path %></li>
        <li><a href="/register">Register</a></li>
        <% else %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.screen_name %><span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "User", user_path %></li>
            <li><%= link_to "Profile", user_profile_path, class: 'meow purr', "data-cats": "yes" %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Logout", logout_path %></li>
          </ul>
        </li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/users/show.html.erb
User Profile